Cleaning data

In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import string
from nltk.corpus import stopwords
from textblob import TextBlob
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer 

In [2]:
total_df = pd.read_pickle('total_df.pkl')

In [3]:
temp = total_df.loc[200:400,:]
temp['keyword'].value_counts()
temp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 200 to 400
Data columns (total 5 columns):
city       201 non-null object
keyword    201 non-null object
company    201 non-null object
title      201 non-null object
summary    201 non-null object
dtypes: object(5)
memory usage: 9.4+ KB


In [4]:
tlist = temp['summary']

In [5]:
from nltk.corpus import stopwords


nlist = []

rx = re.compile(r'(?<=[a-z])(?=[A-Z])')

for i in tlist:
    cln = i.replace('\n',' ')
    cln = rx.sub(' ',cln)
    #cln = [w for w in cln if w.lower() not in stopwords.words('english')]
    cln =''.join( [w for w in cln if w not in string.punctuation])
    cln = cln.lower()
    nlist.append (cln)

In [8]:
nlist[70:75]

['as director of cloud you are an integral member of a team of talented software engineers committed to developing worldclass software products that will revolutionize the mobile internet industry directly contributing to companys strong drive to be on the cutting edge of technology you will lead the development and deployment of the companys admin servers and overall servers scalability for companys cloud on awss3 and private clouds  main responsibilities and requirements architect and lead the development of company scalable cloud ownership of companys admin servers based on a large set of java and my sql development and its no sql extensions supporting functionalities from registration authentication to social networks and self help lead the roadmap to scalability based on sharding and no sql platforms as necessary to support 100m subscribers lead the integration with mobile network operators collaborate with the verification and qa team for endtoend testing between the client and s

In [9]:
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.feature_extraction.text import TfidfTransformer

In [15]:


vectorizer = CountVectorizer(stop_words={'english'},min_df=10, ngram_range=(1,2))

cv = vectorizer.fit_transform(nlist)
cv.shape
vectorizer.get_feature_names()

['10',
 '100',
 '100 paid',
 '100m',
 '100m subscribers',
 '10m',
 '10m consumers',
 '15',
 '15 cities',
 '2012',
 '2012 celerans',
 '2015',
 '327453493mh1234applymaxhirenet',
 '40',
 '401k',
 '401k jamba',
 '50',
 'ability',
 'ability to',
 'able',
 'able to',
 'about',
 'about it',
 'about the',
 'above',
 'access',
 'access to',
 'account',
 'accounting',
 'accuracy',
 'accurate',
 'accurately',
 'achieve',
 'across',
 'across all',
 'across the',
 'act',
 'action',
 'action employer',
 'actionable',
 'active',
 'actively',
 'activities',
 'activity',
 'ad',
 'addition',
 'addition to',
 'additional',
 'address',
 'admin',
 'admin servers',
 'administration',
 'advance',
 'advanced',
 'affirmative',
 'against',
 'age',
 'agencies',
 'agency',
 'agile',
 'algorithms',
 'all',
 'all aspects',
 'all levels',
 'all qualified',
 'along',
 'along with',
 'also',
 'also working',
 'amazing',
 'amazon',
 'amazon aws',
 'america',
 'america and',
 'among',
 'an',
 'an agile',
 'an celeran',


In [13]:
tf_transformer = TfidfTransformer(use_idf=True).fit(cv)
cv_tfidf = tf_transformer.transform(cv)
cv_tfidf.shape
cv_tfidf.indices
cv_tfidf.maxprint
cv_tfidf.minimum
print(cv_tfidf.sorted_indices())


  (0, 7)	0.0206812291757
  (0, 13)	0.0581409107153
  (0, 16)	0.0278285433904
  (0, 21)	0.0123695778643
  (0, 23)	0.0235870039572
  (0, 24)	0.0525698254007
  (0, 27)	0.0267647043912
  (0, 28)	0.0272776105732
  (0, 30)	0.0246260209268
  (0, 31)	0.0290704553577
  (0, 45)	0.0196612498375
  (0, 46)	0.0204657302909
  (0, 47)	0.131424563502
  (0, 51)	0.0516684353689
  (0, 58)	0.0284235961648
  (0, 61)	0.0241780181178
  (0, 64)	0.0262849127003
  (0, 67)	0.0140463618029
  (0, 75)	0.0169170026456
  (0, 82)	0.0273929058776
  (0, 83)	0.0187644783402
  (0, 84)	0.0250073450726
  (0, 96)	0.0232706076561
  (0, 97)	0.200723156117
  (0, 124)	0.0221246220645
  :	:
  (200, 2152)	0.0457231963814
  (200, 2168)	0.0309305049119
  (200, 2171)	0.0317958652354
  (200, 2174)	0.0394244546764
  (200, 2175)	0.0327270101564
  (200, 2178)	0.0261489531561
  (200, 2179)	0.0468521514346
  (200, 2182)	0.042887328604
  (200, 2189)	0.0433268437653
  (200, 2191)	0.0378579616338
  (200, 2195)	0.134795971231
  (200, 2207)	0.02

In [ ]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.30, random_state=43)

In [98]:
print(cv_tfidf)
#pd.DataFrame(cv)
#df.head()

  (0, 213)	0.0476348669591
  (0, 501)	0.0261029472047
  (0, 821)	0.0401024924809
  (0, 44)	0.0623976718192
  (0, 355)	0.0390212128873
  (0, 325)	0.0411250287651
  (0, 938)	0.0248537520266
  (0, 519)	0.0272271065075
  (0, 240)	0.0457192555735
  (0, 75)	0.036248235642
  (0, 372)	0.0371056015018
  (0, 35)	0.132179632541
  (0, 1001)	0.0497075040532
  (0, 920)	0.0569838948599
  (0, 232)	0.0126729608074
  (0, 54)	0.459794412492
  (0, 830)	0.148182045206
  (0, 919)	0.138042402076
  (0, 62)	0.0476348669591
  (0, 130)	0.0326732461964
  (0, 841)	0.059953821493
  (0, 897)	0.0425962023329
  (0, 256)	0.0679650965223
  (0, 617)	0.140776405935
  (0, 551)	0.0825738005363
  :	:
  (100, 824)	0.0316675379716
  (100, 453)	0.0513602115285
  (100, 478)	0.0527834053387
  (100, 712)	0.0513602115285
  (100, 99)	0.0333908578283
  (100, 193)	0.10010200027
  (100, 101)	0.0477103839771
  (100, 560)	0.0579921653268
  (100, 933)	0.0438439120583
  (100, 7)	0.0560656576321
  (100, 406)	0.0477103839771
  (100, 924)	0.0

In [56]:
## Training a classifier
keyword_target = temp['keyword']

from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(cv_tfidf, keyword_target)

In [76]:
clf.class_count_
clf.classes_
clf.get_params()
clf.score(cv_tfidf, keyword_target)
clf.feature_count_
clf.coef_
clf.predict(cv_tfidf)

array(['data+architect', 'data+engineer', 'data+architect',
       'data+architect', 'data+analyst', 'data+analyst', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+analyst', 'data+analyst',
       'data+analyst', 'data+engineer', 'data+analyst', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+engineer', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+analyst', 'data+engineer',
       'data+engineer', 'data+engineer', 'data+engineer', 'data+analyst',
       'data+engineer', 'data+engineer', 'data+analyst', 'data+engineer',
       'data+engineer', 'data+analyst', 'data+analyst', 'data+analyst',
       'data+engineer', 'data+engineer', 'data+engineer', 'data+engineer',
       'data+engineer', 'data+engineer', 'data+engineer', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+analyst', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+analyst', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+analyst', 'data+analyst'

In [88]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report


In [85]:
print(classification_report(keyword_target,clf.predict(cv_tfidf)))

                precision    recall  f1-score   support

  data+analyst       0.68      1.00      0.81        45
data+architect       1.00      0.22      0.36        18
 data+engineer       0.58      0.78      0.67        23
data+scientist       0.00      0.00      0.00        14
  statistician       0.00      0.00      0.00         1

   avg / total       0.61      0.66      0.58       101



/home/kmitchell/anaconda2/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [86]:
print(confusion_matrix(keyword_target,clf.predict(cv_tfidf)))

[[45  0  0  0  0]
 [ 7  4  7  0  0]
 [ 5  0 18  0  0]
 [ 9  0  5  0  0]
 [ 0  0  1  0  0]]


In [90]:

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sb

import matplotlib.patches as mpatches


print(precision_recall_fscore_support(keyword_target,clf.predict(cv_tfidf)))

(array([ 0.68181818,  1.        ,  0.58064516,  0.        ,  0.        ]), array([ 1.        ,  0.22222222,  0.7826087 ,  0.        ,  0.        ]), array([ 0.81081081,  0.36363636,  0.66666667,  0.        ,  0.        ]), array([45, 18, 23, 14,  1]))


/home/kmitchell/anaconda2/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [73]:
from textblob import TextBlob
from textblob.np_extractors import ConllExtractor
extractor = ConllExtractor()
blob = TextBlob(nlist[10], np_extractor=extractor)
blob.noun_phrases

WordList(['position title microsoft', 'architect total experience 810 years location chicago ilterm ftecthcontractor', 'date immediate urgent sep 5th job description', 'msbi architect', 'business intelligence implementation client', 'business intelligence', 'tsql ssis', 'multidimensional modeling cube development', 'visualizaton dot net', 'web development experience', 'project management skills experience', 'gathering requirementsexperience', 'onsiteoffshore model experience', 'teams offshore teamsexcellent communication skills', 'business intelligence implementation 7 years expertise', 'tsql ssis', 'business intelligence'])

In [49]:
vectorizer.get_feature_names()

['10',
 '15',
 '20m',
 '24',
 '25',
 '401k',
 '46',
 '50',
 'abilities',
 'ability',
 'able',
 'about',
 'above',
 'access',
 'accessible',
 'accompanied',
 'according',
 'accounts',
 'accurate',
 'achieve',
 'acquisition',
 'across',
 'act',
 'action',
 'active',
 'activities',
 'activity',
 'addition',
 'address',
 'administration',
 'advance',
 'advanced',
 'affirmative',
 'age',
 'agencies',
 'agency',
 'aid',
 'aims',
 'algorithms',
 'all',
 'allow',
 'also',
 'amazon',
 'among',
 'an',
 'analyses',
 'analysis',
 'analyst',
 'analysts',
 'analytic',
 'analytical',
 'analytics',
 'analyze',
 'analyzing',
 'and',
 'andor',
 'angular',
 'annual',
 'any',
 'app',
 'appealing',
 'applicable',
 'applicant',
 'applicants',
 'application',
 'applications',
 'apply',
 'approach',
 'appropriate',
 'architect',
 'architects',
 'architectural',
 'architecture',
 'architectures',
 'are',
 'area',
 'areas',
 'around',
 'as',
 'aspects',
 'assess',
 'assessment',
 'assessments',
 'asset',
 'assi

In [50]:
from sklearn.feature_extraction.text import TfidfTransformer

[[0 0 0 ..., 0 0 1]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 1 0]]
