In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import string
from nltk.corpus import stopwords
from textblob import TextBlob
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer 

In [2]:
total_df = pd.read_pickle('total_df.pkl')

In [23]:
temp = total_df.loc[200:400,:]
print(temp['keyword'].value_counts())
temp.info()

data+analyst      60
data+architect    57
data+engineer     54
data+scientist    28
statistician       2
Name: keyword, dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 200 to 400
Data columns (total 5 columns):
city       201 non-null object
keyword    201 non-null object
company    201 non-null object
title      201 non-null object
summary    201 non-null object
dtypes: object(5)
memory usage: 9.4+ KB


In [25]:
#tlist = temp['summary']
tlist = total_df['summary']

#keyword_target = temp['keyword']
keyword_target = total_df['keyword']

In [33]:
from nltk.corpus import stopwords
nlist = []

rx = re.compile(r'(?<=[a-z])(?=[A-Z])')
cnt = 0

for i in tlist:
    cln = i.replace('\n',' ')
    cln = cln.replace('•','')
    cln = rx.sub(' ',cln)
    cln = ' '.join([word for word in cln.split() if word not in stopwords.words('english')])
    cln =''.join( [w for w in cln if w not in string.punctuation])
    cln = cln.lower()
    nlist.append (cln)
    cnt += 1
    if cnt % 100 == 0 : print(cnt,cln[:200])

100 ideal candidate  an aspiring analyst quantitative background strong desire make impact business decisions data you appreciate power datadriven environment predictive analytics introduction team busine
200 setup perform report test analysis results moderate high complexity departments laboratory performs documents manufacturers recommended preventive maintenance procedures instruments workgathers pm qc 
300 the mount sinai health system background mount sinai one leading us health systems topranked academic medical center we transforming business focus population health – goal keep entire communities hea
400 title  reporting analyst  marketing location  bellevue wa compensation 31hour  depending experience we searching talented digital marketing analyst exceptional skills building datadriven models suppor
500 overview deloitte one leading professional services organizations united states specializing audit tax consulting financial advisory services clients 20 industries we provide p

In [34]:
import joblib

joblib.dump(nlist,'nlist.pkl')

['nlist.pkl']

In [36]:
nlist[1001:1003]

['job description the game development team seeking unity developer eager help architect new game engine unity you assist building new team game engine unity work artists animators asset pipeline collaborate platform developers unity features capabilities responsibilities create clean efficient well tested code assist architecting new game engine create modify games unity help establish process pipeline asset creation incorporation games participate team meetings relating designing system architecture analyze organize optimize code research new gameauthoring technology requirements 3 years experience working unity strong background c c strong understanding objectoriented programming data structures experience eventdriven systems degree computer science electrical computer engineering ece game development what we will offer to you competitive salary  annual bonus generous paid time off latest technology work  life balance complete insurance coverage medical dental vision life 401k compa

In [ ]:
X = nlist
y = keyword_target

In [ ]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.30, random_state=43)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.feature_extraction.text import TfidfTransformer

In [14]:
vectorizer = CountVectorizer(stop_words={'english'},min_df=20, ngram_range=(1,2))

cv = vectorizer.fit_transform(nlist)
cv.shape
#vectorizer.get_feature_names()

['100',
 '100 paid',
 '100m',
 '100m subscribers',
 '10m',
 '10m consumers',
 '15',
 '15 cities',
 '2012',
 '2012 icelerans',
 '327453493mh1234applymaxhirenet',
 '401k',
 '401k jamba',
 'ability',
 'ability work',
 'able',
 'about',
 'access',
 'across',
 'action',
 'action employer',
 'activities',
 'addition',
 'addition end',
 'admin',
 'admin servers',
 'advanced',
 'age',
 'agile',
 'all',
 'also',
 'also working',
 'amazon',
 'amazon aws',
 'america',
 'america asia',
 'analysis',
 'analyst',
 'analysts',
 'analytical',
 'analytics',
 'analyze',
 'analyzing',
 'and',
 'andor',
 'anywhere',
 'anywhere internet',
 'applicants',
 'application',
 'application servers',
 'applications',
 'apply',
 'appropriate',
 'architect',
 'architect lead',
 'architecture',
 'are',
 'area',
 'areas',
 'around',
 'around world',
 'as',
 'as director',
 'asia',
 'asia responsible',
 'assigned',
 'assist',
 'at',
 'attachment',
 'attachment to',
 'authentication',
 'authentication social',
 'availabl

In [15]:
tf_transformer = TfidfTransformer(use_idf=True).fit(cv)
cv_tfidf = tf_transformer.transform(cv)
cv_tfidf.shape
#cv_tfidf.indices
#cv_tfidf.maxprint
#cv_tfidf.minimum
#print(cv_tfidf.sorted_indices())

  (0, 6)	0.0420201222989
  (0, 16)	0.0411567564888
  (0, 22)	0.039947728237
  (0, 29)	0.0429358444509
  (0, 30)	0.0285393984949
  (0, 36)	0.0556569073007
  (0, 42)	0.0472812216029
  (0, 43)	0.0434154018564
  (0, 44)	0.064463629421
  (0, 47)	0.177691044123
  (0, 48)	0.06095713799
  (0, 52)	0.173661607426
  (0, 85)	0.148363945925
  (0, 89)	0.0840402445978
  (0, 90)	0.0958481512413
  (0, 96)	0.0958481512413
  (0, 116)	0.0236138547137
  (0, 168)	0.035602351085
  (0, 175)	0.0492981851824
  (0, 180)	0.0492981851824
  (0, 201)	0.0755239475817
  (0, 211)	0.0976929338918
  (0, 221)	0.0449528080304
  (0, 253)	0.0444227610308
  (0, 259)	0.0449528080304
  :	:
  (200, 830)	0.0643043043337
  (200, 831)	0.0329053046776
  (200, 846)	0.208279155551
  (200, 852)	0.0288965656495
  (200, 868)	0.0318284498503
  (200, 874)	0.0478406798788
  (200, 880)	0.0422868744308
  (200, 883)	0.0660398550758
  (200, 886)	0.0342363686598
  (200, 888)	0.0550483686793
  (200, 908)	0.0791597539503
  (200, 917)	0.04906039554

In [16]:
## Training a classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(cv_tfidf, keyword_target)

In [17]:
clf.class_count_
clf.classes_
clf.get_params()
clf.score(cv_tfidf, keyword_target)
clf.feature_count_
clf.coef_
clf.predict(cv_tfidf)

array(['data+analyst', 'data+analyst', 'data+engineer', 'data+engineer',
       'data+analyst', 'data+engineer', 'data+engineer', 'data+analyst',
       'data+engineer', 'data+engineer', 'data+analyst', 'data+engineer',
       'data+engineer', 'data+engineer', 'data+engineer', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+engineer', 'data+engineer',
       'data+analyst', 'data+engineer', 'data+analyst', 'data+analyst',
       'data+engineer', 'data+engineer', 'data+engineer', 'data+analyst',
       'data+analyst', 'data+engineer', 'data+engineer', 'data+engineer',
       'data+analyst', 'data+analyst', 'data+engineer', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+engineer', 'data+engineer',
       'data+analyst', 'data+analyst', 'data+analyst', 'data+engineer',
       'data+engineer', 'data+engineer', 'data+analyst', 'data+analyst',
       'data+analyst', 'data+analyst', 'data+analyst', 'data+analyst',
       'data+architect', 'data+architect', 'data+arc

In [18]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report


In [19]:
print(classification_report(keyword_target,clf.predict(cv_tfidf)))

                precision    recall  f1-score   support

  data+analyst       0.60      0.98      0.75        60
data+architect       1.00      0.49      0.66        57
 data+engineer       0.60      0.83      0.70        54
data+scientist       0.00      0.00      0.00        28
  statistician       0.00      0.00      0.00         2

   avg / total       0.62      0.66      0.60       201



/home/kmitchell/anaconda2/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [20]:
print(confusion_matrix(keyword_target,clf.predict(cv_tfidf)))

[[59  0  1  0  0]
 [14 28 15  0  0]
 [ 9  0 45  0  0]
 [15  0 13  0  0]
 [ 1  0  1  0  0]]


In [21]:
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sb

import matplotlib.patches as mpatches


print(precision_recall_fscore_support(keyword_target,clf.predict(cv_tfidf)))

(array([ 0.60204082,  1.        ,  0.6       ,  0.        ,  0.        ]), array([ 0.98333333,  0.49122807,  0.83333333,  0.        ,  0.        ]), array([ 0.74683544,  0.65882353,  0.69767442,  0.        ,  0.        ]), array([60, 57, 54, 28,  2]))


/home/kmitchell/anaconda2/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [22]:
from textblob import TextBlob
from textblob.np_extractors import ConllExtractor
extractor = ConllExtractor()
blob = TextBlob(nlist[10], np_extractor=extractor)
blob.noun_phrases

WordList(['looking amazing datadriven marketer marketing strategy ce capillary electrophoresis business', 'sanger sequencing fragment analysis multiplex pcr analysis sizing glycanprotein analysis', 'director marketing', 'interfaces senior leadership works', 'functional global team resources', 'marketing rd finance regulatory', 'marketing management opportunities', 'business reporting head business unit', 'global crossfunctional business teams', 'annual growth profitability objectives product lines', 'marketing director role guides business market development marketing communications strategy', 'marketing core team member key', 'functional programs innovation teams support marketing activities products preconcept', 'addition person responsible', 'global regional marketing teams', 'support refinement marketing plans execution', '’ ll architect demand generation marketing strategy programs', 'demand engagement influence sales', 'drive new product', 'plans collaboration product management'